/*product_export*/
SELECT P.PRODUCT_ID,
       P.PSEUDO_ID,
       P.PRODUCT_TYPE_ENUM_ID,
       P.OWNER_PARTY_ID,
       P.PRODUCT_NAME,
       PI.ID_VALUE 'UPC',
       PI2.ID_VALUE 'SKU',
       #PCM.PRODUCT_CATEGORY_ID,
       P.AMOUNT_UOM_ID,
       P.LAST_UPDATED_STAMP
FROM PRODUCT P
LEFT JOIN PRODUCT_IDENTIFICATION PI ON P.PRODUCT_ID = PI.PRODUCT_ID AND PI.PRODUCT_ID_TYPE_ENUM_ID = 'PidtUpca'
LEFT JOIN PRODUCT_IDENTIFICATION PI2 ON P.PRODUCT_ID = PI2.PRODUCT_ID AND PI2.PRODUCT_ID_TYPE_ENUM_ID = 'PidtSku'
#LEFT JOIN PRODUCT_CATEGORY_MEMBER PCM ON PCM.PRODUCT_ID = P.PRODUCT_ID AND PCM.PRODUCT_CATEGORY_ID = ''
WHERE P.OWNER_PARTY_ID IN ('HRLY')
AND P.PRODUCT_TYPE_ENUM_ID = 'PtAsset'
AND PI.ID_VALUE IN (
'882700792405','882700792412','882700792429','882700792436','882700792566','882700792573','882700792580','882700792597','882700792481','882700792498','882700792504','882700792511','882700792641','882700792658','882700792665','882700792672','882700028474','882700028481','882700028498','882700028504','629211476840','629211476857','629211476864','629211476871','629211476758','629211476765','629211476772','629211476789','197057198610','197057198627','197057198634','197057198641','197057198665','197057198672','197057198689','197057198696','197057198702','197057198726','197057198948','197057198955','197057198962','197057198979','197057198993','197057198764','197057198771','197057198788','197057198795','197057198818','197057198825','197057198832','197057198849','197057198856','197057198870','197057198436','197057198443','197057198450','197057198467','197057198481','197057219988','197057219995','197057220007','197057220014','197057220038','197057200054','197057200061','197057200078','197057200085','197057200108','197057200115','197057200122','197057200139','197057200146','197057200160'
    );

/*product_findDuplicatesInCategory*/
SELECT PCM.PRODUCT_ID,
       P.PSEUDO_ID,
       PCM.PRODUCT_CATEGORY_ID,
       COUNT(PCM.PRODUCT_CATEGORY_ID)
FROM PRODUCT_CATEGORY_MEMBER PCM
INNER JOIN PRODUCT P ON P.PRODUCT_ID = PCM.PRODUCT_ID AND P.OWNER_PARTY_ID = 'HONEYWELL'
GROUP BY PCM.PRODUCT_ID, PCM.PRODUCT_CATEGORY_ID
HAVING COUNT(PCM.PRODUCT_CATEGORY_ID) > 1;

/*product_exportWithPrice*/
SELECT P.PRODUCT_ID,
       P.PSEUDO_ID,
       P.PRODUCT_TYPE_ENUM_ID,
       P.OWNER_PARTY_ID,
       P.PRODUCT_NAME,
       PI.ID_VALUE 'UPC',
       PI2.ID_VALUE 'SKU',
       PP.PRICE 'LISTPRICE',
       PPCOST.PRICE 'COST'
FROM PRODUCT P
LEFT JOIN PRODUCT_IDENTIFICATION PI ON P.PRODUCT_ID = PI.PRODUCT_ID AND PI.PRODUCT_ID_TYPE_ENUM_ID = 'PidtUpca'
LEFT JOIN PRODUCT_IDENTIFICATION PI2 ON P.PRODUCT_ID = PI2.PRODUCT_ID AND PI2.PRODUCT_ID_TYPE_ENUM_ID = 'PidtSku'
LEFT JOIN PRODUCT_PRICE PP ON PP.PRODUCT_ID = P.PRODUCT_ID AND PP.PRICE_TYPE_ENUM_ID = 'PPTLIST' AND PP.THRU_DATE IS NULL
LEFT JOIN PRODUCT_PRICE PPCOST ON PPCOST.PRODUCT_ID = P.PRODUCT_ID AND PPCOST.PRICE_TYPE_ENUM_ID = 'PPTAVERAGE' AND PPCOST.THRU_DATE IS NULL
WHERE P.OWNER_PARTY_ID = 'FOHW'
AND P.PRODUCT_TYPE_ENUM_ID = 'PtAsset';


/*asset_summary*/
SELECT A.STATUS_ID,
       A.OWNER_PARTY_ID,
       A.PRODUCT_ID,
       P.PSEUDO_ID,
       PI.ID_VALUE,
       SUM(A.QUANTITY_ON_HAND_TOTAL),
       SUM(A.AVAILABLE_TO_PROMISE_TOTAL),
       A.FACILITY_ID,
       A.LOCATION_SEQ_ID,
       A.CONTAINER_ID,
       A.ASSET_POOL_ID
FROM ASSET A
INNER JOIN PRODUCT P ON P.PRODUCT_ID = A.PRODUCT_ID
INNER JOIN PRODUCT_IDENTIFICATION PI ON PI.PRODUCT_ID = P.PRODUCT_ID
    AND PI.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
WHERE A.OWNER_PARTY_ID = 'JKFD' AND A.QUANTITY_ON_HAND_TOTAL > 0
AND A.FACILITY_ID IN ('JKFD_FACILITY')
AND A.STATUS_ID = 'ASTAVAILABLE'
GROUP BY A.STATUS_ID, A.OWNER_PARTY_ID, A.PRODUCT_ID, P.PSEUDO_ID, PI.ID_VALUE, A.FACILITY_ID, A.LOCATION_SEQ_ID, A.CONTAINER_ID, A.ASSET_POOL_ID;

SELECT SUM(A.QUANTITY_ON_HAND_TOTAL),
       SUM(A.AVAILABLE_TO_PROMISE_TOTAL),
       A.PRODUCT_ID,
       A.FACILITY_ID,
       A.OWNER_PARTY_ID,
       A.STATUS_ID
FROM ASSET A
WHERE A.OWNER_PARTY_ID = 'JKFD' AND A.FACILITY_ID = 'JKFD_FACILITY' AND A.QUANTITY_ON_HAND_TOTAL > 0
GROUP BY A.STATUS_ID, A.OWNER_PARTY_ID, A.FACILITY_ID;

SELECT A.STATUS_ID,
       A.OWNER_PARTY_ID,
       A.PRODUCT_ID,
       P.PSEUDO_ID,
       PI.ID_VALUE,
       SUM(A.QUANTITY_ON_HAND_TOTAL),
       SUM(A.AVAILABLE_TO_PROMISE_TOTAL),
       A.FACILITY_ID
FROM ASSET A
INNER JOIN PRODUCT P ON P.PRODUCT_ID = A.PRODUCT_ID
INNER JOIN PRODUCT_IDENTIFICATION PI ON PI.PRODUCT_ID = P.PRODUCT_ID
    AND PI.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
WHERE P.OWNER_PARTY_ID = 'HTF' AND A.OWNER_PARTY_ID = 'HTF'
AND A.FACILITY_ID = 'NOG_DC_PITTSBURGH_FACILITY'
GROUP BY A.STATUS_ID, A.OWNER_PARTY_ID, A.PRODUCT_ID, A.FACILITY_ID;


SELECT P.PSEUDO_ID,
       SUM(A.AVAILABLE_TO_PROMISE_TOTAL),
       SUM(A.QUANTITY_ON_HAND_TOTAL)
FROM ASSET A
INNER JOIN PRODUCT P ON P.PRODUCT_ID = A.PRODUCT_ID
WHERE A.OWNER_PARTY_ID = 'HRLY'
AND A.STATUS_ID = 'ASTAVAILABLE'
# AND A.FACILITY_ID = 'BOL_DC_FONTANA'
# AND P.PSEUDO_ID LIKE ('KP0070-CHERRY%')
AND A.QUANTITY_ON_HAND_TOTAL > 0
GROUP BY P.PSEUDO_ID;



/*leftover_reservations*/
SELECT *
FROM ASSET_RESERVATION AR
INNER JOIN ORDER_ITEM OI ON OI.PRODUCT_ID = AR.PRODUCT_ID AND OI.ORDER_ID = AR.ORDER_ID
INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID = OI.ORDER_ID
WHERE OH.STATUS_ID = 'ORDERCANCELLED';

/*prod_facilities*/
SELECT PSF.PRODUCT_STORE_ID,
       PSF.FACILITY_ID,
       F.OWNER_PARTY_ID,
       F.FACILITY_NAME
FROM PRODUCT_STORE_FACILITY PSF
INNER JOIN FACILITY F ON F.FACILITY_ID = PSF.FACILITY_ID
WHERE PSF.PRODUCT_STORE_ID = 'BROOK_SHOPIFY';


/*orderandreturn_items*/
SELECT OH.DISPLAY_ID,
       OH.PLACED_DATE,
       OI.ORDER_ID,
       OI.PRODUCT_ID,
       OI.OTHER_PARTY_PRODUCT_ID,
       OI.ITEM_DESCRIPTION,
       OI.QUANTITY 'ORDER QTY',
       RI.RETURN_ID,
       RI.RETURN_QUANTITY 'RETURN QTY'
FROM ORDER_ITEM OI
INNER JOIN ORDER_HEADER OH on OI.ORDER_ID = OH.ORDER_ID AND OI.ITEM_TYPE_ENUM_ID = 'ItemProduct'
LEFT JOIN RETURN_ITEM RI ON RI.ORDER_ID = OI.ORDER_ID AND RI.PRODUCT_ID = OI.PRODUCT_ID
LEFT JOIN RETURN_HEADER RH ON RH.RETURN_ID = RI.RETURN_ID
WHERE OH.PRODUCT_STORE_ID = 'KK_SHOPIFY'
AND OH.STATUS_ID IN ('ORDERCOMPLETED','ORDERAPPROVED')
AND OH.PLACED_DATE BETWEEN '2024-02-05 03:00:00' AND '2024-11-30 21:00:00';

/*monitor_servicejob*/
SELECT SJR.JOB_NAME,
        MAX(SJR.JOB_RUN_ID),
        SJR.HAS_ERROR,
        SJR.START_TIME,
        MAX(SJR.END_TIME)
FROM SERVICE_JOB_RUN SJR
INNER JOIN SERVICE_JOB SJ ON SJ.JOB_NAME = SJR.JOB_NAME AND SJ.PAUSED <> 'Y'
GROUP BY SJR.JOB_NAME;

/*brook_vendorOrderFulfillmentDelay*/
SELECT OH.DISPLAY_ID,
       OH.PRODUCT_STORE_ID,
       OH.ORDER_ID,
       OP.ORDER_PART_SEQ_ID,
       S.SHIPMENT_ID,
       OP.FACILITY_ID,
       OH.ENTRY_DATE,
       S.PACKED_DATE
FROM ORDER_ITEM OI
INNER JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.ORDER_ID = OI.ORDER_ID AND OI.PRODUCT_ID = SIS.PRODUCT_ID
INNER JOIN SHIPMENT S ON S.SHIPMENT_ID = SIS.SHIPMENT_ID
INNER JOIN ORDER_PART OP ON OP.ORDER_ID = OI.ORDER_ID AND OP.ORDER_PART_SEQ_ID = OI.ORDER_PART_SEQ_ID
INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID = OP.ORDER_ID
WHERE OH.PRODUCT_STORE_ID = 'BROOK_SHOPIFY'
GROUP BY OI.ORDER_ID,OI.ORDER_PART_SEQ_ID,S.SHIPMENT_ID;


/*product_exportAndQuantity*/
SELECT P.PRODUCT_ID,
       P.PSEUDO_ID,
       P.PRODUCT_TYPE_ENUM_ID,
       P.OWNER_PARTY_ID,
       P.PRODUCT_NAME,
       PI.ID_VALUE 'UPC',
       PI2.ID_VALUE 'SKU',
       PCM.PRODUCT_CATEGORY_ID,
       SUM(A.AVAILABLE_TO_PROMISE_TOTAL)
FROM PRODUCT P
LEFT JOIN PRODUCT_IDENTIFICATION PI ON P.PRODUCT_ID = PI.PRODUCT_ID AND PI.PRODUCT_ID_TYPE_ENUM_ID = 'PidtUpca'
LEFT JOIN PRODUCT_IDENTIFICATION PI2 ON P.PRODUCT_ID = PI2.PRODUCT_ID AND PI2.PRODUCT_ID_TYPE_ENUM_ID = 'PidtSku'
LEFT JOIN PRODUCT_CATEGORY_MEMBER PCM ON PCM.PRODUCT_ID = P.PRODUCT_ID AND PCM.PRODUCT_CATEGORY_ID = 'CSWK_SHOPIFY'
LEFT JOIN ASSET A ON A.PRODUCT_ID = P.PRODUCT_ID
WHERE P.OWNER_PARTY_ID = 'CSWK'
AND P.PRODUCT_TYPE_ENUM_ID = 'PtAsset'
#AND P.PSEUDO_ID LIKE 'OSS-000%'
GROUP BY A.PRODUCT_ID;


/*kk_refundAudit*/
SELECT RH.RETURN_ID,
       RH.STATUS_ID,
       RH.VENDOR_PARTY_ID,
       RH.ENTRY_DATE,
       RH.FACILITY_ID,
       RH.DISPLAY_ID,
       RH.EXTERNAL_ID,
       RH.ORIGIN_ID,
       RI.RETURN_ITEM_SEQ_ID,
       RI.PRODUCT_ID,
       RI.DESCRIPTION,
       RI.STATUS_ID,
       RI.RETURN_QUANTITY,
       RI.RECEIVED_QUANTITY
FROM RETURN_HEADER RH
INNER JOIN RETURN_ITEM RI ON RI.RETURN_ID = RH.RETURN_ID AND RI.ITEM_TYPE_ENUM_ID = 'ITEMPRODUCT'
WHERE RH.VENDOR_PARTY_ID = 'KK'
AND RH.STATUS_ID <> 'RETURNCOMPLETED'
AND RI.RECEIVED_QUANTITY > 0;


SELECT
	OH.ORDER_ID as 'Encore ID',
	OH.PLACED_DATE as 'Order Date',
	OH.STATUS_ID as 'Status',
	OH.PRODUCT_STORE_ID as 'Store',
	OH.DISPLAY_ID as 'End Customer Order Number',
	OH.EXTERNAL_ID as 'Upstream System ID',
	OP.OTHER_PARTY_ORDER_ID as 'PO Number',
	M940.SYSTEM_MESSAGE_ID as '940 ID',
	M940.ACK_MESSAGE_ID as '940 ACK ID',
	GROUP_CONCAT(DISTINCT SIS.SHIPMENT_ID) AS 'Encore Shipment ID',
	GROUP_CONCAT(DISTINCT M945.DOC_CONTROL) as '945 ID',
	GROUP_CONCAT(DISTINCT M870.SYSTEM_MESSAGE_ID) as '870 ID'
FROM
	ORDER_HEADER OH
	INNER JOIN ORDER_PART OP ON OP.ORDER_ID = OH.ORDER_ID
	LEFT JOIN SYSTEM_MESSAGE M940 ON M940.ORDER_ID=OH.ORDER_ID AND M940.DOC_SUB_TYPE='940'
	LEFT JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.ORDER_ID=OH.ORDER_ID AND SIS.STATUS_ID='SisPacked'
	LEFT JOIN SHIPMENT_SYSTEM_MESSAGE SSM ON SSM.SHIPMENT_ID=SIS.SHIPMENT_ID
	LEFT JOIN SYSTEM_MESSAGE M945 ON M945.SYSTEM_MESSAGE_ID=SSM.SYSTEM_MESSAGE_ID AND M945.DOC_SUB_TYPE='945'
	LEFT JOIN ORDER_SYSTEM_MESSAGE OSM870 ON OSM870.ORDER_ID=OH.ORDER_ID
	LEFT JOIN SYSTEM_MESSAGE M870 ON M870.SYSTEM_MESSAGE_ID=OSM870.SYSTEM_MESSAGE_ID AND M870.DOC_SUB_TYPE='870'
WHERE
	OP.VENDOR_PARTY_ID = 'HONEYWELL'
	AND OH.PRODUCT_STORE_ID NOT IN('HPPE_SHOPIFY', 'HOWARDLEIGHT_SHOPIFY')
	AND OH.PLACED_DATE > '2021-04-19 10:00'
	GROUP BY OH.ORDER_ID;

/*kk_checkEdiOrder850*/
SELECT OH.ORDER_ID,
       OH.DISPLAY_ID,
       OH.ENTRY_DATE,
       OH.STATUS_ID,
       OH.PRODUCT_STORE_ID,
       OP.FACILITY_ID,
       SM.MESSAGE_ID,
       SM.DOC_SUB_TYPE
FROM ORDER_HEADER OH
LEFT JOIN SYSTEM_MESSAGE SM ON SM.ORDER_ID = OH.ORDER_ID AND SM.DOC_SUB_TYPE = '850'
INNER JOIN ORDER_PART OP ON OP.ORDER_ID = OH.ORDER_ID AND OP.FACILITY_ID <> 'PREORDER'
WHERE OH.ENTRY_DATE > '2021-06-01'
AND OH.PRODUCT_STORE_ID = 'KK_SHOPIFY'
AND SM.DOC_SUB_TYPE IS NULL;

/*checkAllOrderProcess*/
SELECT * FROM ORDER_PROCESS OP
    INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID=OP.ORDER_ID
WHERE OP.STATUS_ID='EsNotStarted';

/*just_AssetOnHandSummary_info*/
SELECT P.PSEUDO_ID AS       'Product ID',
       P.PRODUCT_NAME AS    'Product Name',
       '' AS                'Starting',
       '' AS                'Shipments In',
       '' AS                'Other Receipts',
       '' AS                'Returns',
       '' AS                'Shipments Out',
       '' AS                'Adjustments',
       '' AS                'Change',
       '' AS                'Ending',
       PI_UPCA.ID_VALUE AS     'UPC',
       PP_COST.PRICE AS                'Cost',
       PP_ORIG.PRICE AS                'Original Retail Price',
       PP_CURRENT.PRICE AS                'Current Retail Price',
       '' AS                'Receipt Date',
       '' AS                'Season',
       '' AS                'Brand',
       '' AS                'Vendor',
       '' AS                'Origin Facility ID',
       '' AS                'Inbound PO'
FROM PRODUCT P
LEFT JOIN PRODUCT_IDENTIFICATION PI_UPCA ON PI_UPCA.PRODUCT_ID = P.PRODUCT_ID AND PI_UPCA.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
LEFT JOIN PRODUCT_PRICE PP_COST ON PP_COST.PRODUCT_ID = P.PRODUCT_ID AND PP_COST.PRICE_TYPE_ENUM_ID = 'PPTAVERAGE' AND PP_COST.THRU_DATE IS NULL AND PP_COST.PRODUCT_STORE_ID = 'JUST_SHOPIFY'
LEFT JOIN PRODUCT_PRICE PP_ORIG ON PP_ORIG.PRODUCT_ID = P.PRODUCT_ID AND PP_ORIG.PRICE_TYPE_ENUM_ID = 'PPTLIST' AND PP_ORIG.THRU_DATE IS NULL AND PP_ORIG.PRODUCT_STORE_ID = 'JUST_SHOPIFY'
LEFT JOIN PRODUCT_PRICE PP_CURRENT ON PP_CURRENT.PRODUCT_ID = P.PRODUCT_ID AND PP_CURRENT.PRICE_TYPE_ENUM_ID = 'PPTCURRENT' AND PP_CURRENT.THRU_DATE IS NULL AND PP_CURRENT.PRODUCT_STORE_ID = 'JUST_SHOPIFY'
WHERE P.OWNER_PARTY_ID = 'JUST'
AND P.PRODUCT_TYPE_ENUM_ID = 'PTASSET';

/*integrationProduct_statusCheck*/
SELECT IP.INTEGRATION_PRODUCT_STATUS_ID,
       COUNT(ALL INTEGRATION_PRODUCT_ID)
FROM INTEGRATION_PRODUCT IP
WHERE IP.INTEGRATION_ID = 'FRYE_SHOPIFY'
GROUP BY IP.INTEGRATION_PRODUCT_STATUS_ID;


/*brookstone_facilities*/
SELECT *
FROM PRODUCT_STORE_FACILITY
WHERE PRODUCT_STORE_ID = 'HRLY_SHOPIFY'
ORDER BY SEQUENCE_NUM DESC;


SELECT RH.RETURN_ID,
       RH.LAST_UPDATED_STAMP,
       OH.DISPLAY_ID,
       IEML.REQUEST,
       IEML.RESPONSE
FROM RETURN_HEADER RH
INNER JOIN ORDER_HEADER OH ON OH.DISPLAY_ID = RH.DISPLAY_ID
LEFT JOIN INTEGRATION_EXTERNAL_MESSAGE_LOG IEML ON IEML.INTERNAL_ID = OH.ORDER_ID AND IEML.SERVICE_NAME = 'brandedonline.shopify.admin.order.OrderServices.refund#ItemsInOrder'
WHERE RH.STATUS_ID = 'RETURNCOMPLETED'
AND IEML.RESPONSE IS NULL
AND IEML.REQUEST IS NOT NULL
AND RH.LAST_UPDATED_STAMP > '2021-08-01'
LIMIT 50;


/*srio_ShipNotice*/
SELECT OH.DISPLAY_ID AS 'ORDER',
       '' AS 'BOX SHIP VIA',
       SPRS.TRACKING_CODE AS 'TRACKING NO',
       DATE_FORMAT(S.LAST_UPDATED_STAMP, '%m/%d/%y') AS 'ACTUAL SHIP DATE', -- NEED FORMATTING
       '' AS 'ACTUAL SHIP TIME',
       SP.WEIGHT AS 'BOX WEIGHT',
       '0' AS 'BOX FREIGHT AMOUNT',
       OI.EXTERNAL_ITEM_SEQ_ID AS 'ORDER LINE NUMBER',
       P.PSEUDO_ID AS 'ITEM',
       SUM(SPC.QUANTITY) AS 'ITEM QUANTITY',
       '' AS 'SHIPPING BOX ID',
       OH.ORDER_NAME AS 'CUSTOMER REF',
       OH.ORIGIN_ID AS 'ONLINE ID',
       OI.CUSTOMER_REFERENCE_ID AS 'CUSTOMER PO'
FROM SHIPMENT_PACKAGE SP
INNER JOIN SHIPMENT_PACKAGE_CONTENT SPC ON (SP.SHIPMENT_ID = SPC.SHIPMENT_ID
    AND SP.SHIPMENT_PACKAGE_SEQ_ID = SPC.SHIPMENT_PACKAGE_SEQ_ID)
INNER JOIN SHIPMENT_ITEM_SOURCE SIS ON (SIS.SHIPMENT_ID = SPC.SHIPMENT_ID
    AND SIS.PRODUCT_ID = SPC.PRODUCT_ID)
INNER JOIN SHIPMENT S ON S.SHIPMENT_ID = SIS.SHIPMENT_ID
INNER JOIN SHIPMENT_PACKAGE_ROUTE_SEG SPRS ON SPRS.SHIPMENT_ID = SPC.SHIPMENT_ID
    AND SPRS.SHIPMENT_PACKAGE_SEQ_ID = SPC.SHIPMENT_PACKAGE_SEQ_ID
INNER JOIN SHIPMENT_ROUTE_SEGMENT SRS ON SRS.SHIPMENT_ID = SPRS.SHIPMENT_ID
    AND SRS.SHIPMENT_ROUTE_SEGMENT_SEQ_ID = SPRS.SHIPMENT_ROUTE_SEGMENT_SEQ_ID
INNER JOIN ORDER_ITEM OI ON OI.ORDER_ID = SIS.ORDER_ID
    AND OI.ORDER_ITEM_SEQ_ID = SIS.ORDER_ITEM_SEQ_ID
INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID = SIS.ORDER_ID
INNER JOIN PRODUCT P ON OI.PRODUCT_ID = P.PRODUCT_ID
WHERE SP.SHIPMENT_ID IN ('3713033')
#    AND S.STATUS_ID = 'ShipShipped'
    AND S.SHIPMENT_TYPE_ENUM_ID = 'ShpTpSales'
GROUP BY OH.ORDER_ID, P.PSEUDO_ID;

/*katy_TotalShippedCustomer_line*/
SELECT SI.SHIPMENT_ID,
       SI.PRODUCT_ID,
       SI.QUANTITY,
       S.STATUS_ID,
       S.FROM_PARTY_ID,
       S.ENTRY_DATE,
       S.SHIP_BEFORE_DATE,
       S.SHIP_AFTER_DATE,
       PISKU.ID_VALUE AS 'SKU',
       PIUPC.ID_VALUE AS 'UPC',
       PERSON.FIRST_NAME,
       PERSON.LAST_NAME,
       PRODUCT.PRODUCT_NAME,
       S.PACKED_DATE,
       TOPARTY.OWNER_PARTY_ID,
       OH.DISPLAY_ID
FROM SHIPMENT_ITEM SI
INNER JOIN SHIPMENT S ON S.SHIPMENT_ID = SI.SHIPMENT_ID
INNER JOIN PRODUCT ON PRODUCT.PRODUCT_ID = SI.PRODUCT_ID
INNER JOIN PRODUCT_IDENTIFICATION PISKU ON PISKU.PRODUCT_ID = SI.PRODUCT_ID AND PISKU.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTSKU'
INNER JOIN PRODUCT_IDENTIFICATION PIUPC ON PIUPC.PRODUCT_ID = SI.PRODUCT_ID AND PIUPC.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
INNER JOIN PERSON ON PARTY_ID = S.TO_PARTY_ID
INNER JOIN PARTY TOPARTY ON TOPARTY.PARTY_ID = S.TO_PARTY_ID
INNER JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.SHIPMENT_ID = SI.SHIPMENT_ID AND SIS.PRODUCT_ID = SI.PRODUCT_ID
INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID = SIS.ORDER_ID
WHERE TOPARTY.OWNER_PARTY_ID = 'KATY';

/*katy_TotalShippedCustomer_summary*/
SELECT SUM(SI.SHIPMENT_ID),
       SI.PRODUCT_ID,
       SUM(SI.QUANTITY),
       S.STATUS_ID,
       S.FROM_PARTY_ID,
       S.ENTRY_DATE,
       S.SHIP_BEFORE_DATE,
       S.SHIP_AFTER_DATE,
       PISKU.ID_VALUE AS 'SKU',
       PIUPC.ID_VALUE AS 'UPC',
       PERSON.FIRST_NAME,
       PERSON.LAST_NAME,
       PRODUCT.PRODUCT_NAME,
       S.PACKED_DATE,
       TOPARTY.OWNER_PARTY_ID,
       OH.DISPLAY_ID
FROM SHIPMENT_ITEM SI
INNER JOIN SHIPMENT S ON S.SHIPMENT_ID = SI.SHIPMENT_ID
INNER JOIN PRODUCT ON PRODUCT.PRODUCT_ID = SI.PRODUCT_ID
INNER JOIN PRODUCT_IDENTIFICATION PISKU ON PISKU.PRODUCT_ID = SI.PRODUCT_ID AND PISKU.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTSKU'
INNER JOIN PRODUCT_IDENTIFICATION PIUPC ON PIUPC.PRODUCT_ID = SI.PRODUCT_ID AND PIUPC.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
INNER JOIN PERSON ON PARTY_ID = S.TO_PARTY_ID
INNER JOIN PARTY TOPARTY ON TOPARTY.PARTY_ID = S.TO_PARTY_ID
INNER JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.SHIPMENT_ID = SI.SHIPMENT_ID AND SIS.PRODUCT_ID = SI.PRODUCT_ID
INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID = SIS.ORDER_ID
WHERE TOPARTY.OWNER_PARTY_ID = 'KATY';


/*jorge_kkRefundCreditResp*/
SELECT *
FROM RETURN_ITEM RI
         INNER JOIN RETURN_HEADER RH ON RH.RETURN_ID = RI.RETURN_ID AND RI.ITEM_TYPE_ENUM_ID = 'ITEMPRODUCT'
    AND RH.VENDOR_PARTY_ID = 'KK'
    AND RI.RESPONSE_DATE > '2021-12-03' AND RI.RESPONSE_DATE < '2021-12-06'
    AND RI.RETURN_RESPONSE_ENUM_ID = 'RRSPCREDIT';

SELECT *
FROM ASSET A
INNER JOIN PRODUCT P ON P.PRODUCT_ID = A.PRODUCT_ID
INNER JOIN PRODUCT_PRICE PP ON PP.PRODUCT_ID = P.PRODUCT_ID AND PP.PRODUCT_STORE_ID = 'KATY_SHOPIFY' AND PP.THRU_DATE IS NULL AND PP.PRICE_TYPE_ENUM_ID


/*dc2_locationNotEmpty*/
SELECT DISTINCT (LOCATION_SEQ_ID),
                SUM(A.QUANTITY_ON_HAND_TOTAL)
FROM ASSET A
WHERE A.QUANTITY_ON_HAND_TOTAL > 0
  AND A.FACILITY_ID = 'BOL_DC_FONTANA_2'
GROUP BY A.LOCATION_SEQ_ID;

/*emptyLocationReport*/
drop table FACILITY_LOCATION_INVENTORY;

SELECT *
FROM FACILITY_LOCATION_INVENTORY;

CREATE TEMPORARY TABLE FACILITY_LOCATION_INVENTORY
(
    INDEX FAC_LOC_IDX (FACILITY_ID, LOCATION_SEQ_ID),
    INDEX OWNER_FAC_LOC (OWNER_PARTY_ID, FACILITY_ID, LOCATION_SEQ_ID)
)
SELECT A.FACILITY_ID,
       A.LOCATION_SEQ_ID,
       A.OWNER_PARTY_ID,
       FL.LOCATION_TYPE_ENUM_ID,
       A.STATUS_ID,
       SUM(A.QUANTITY_ON_HAND_TOTAL) AS QUANTITY_ON_HAND_TOTAL
FROM ASSET A
         INNER JOIN FACILITY_LOCATION FL ON FL.LOCATION_SEQ_ID = A.LOCATION_SEQ_ID AND FL.FACILITY_ID = A.FACILITY_ID
WHERE A.QUANTITY_ON_HAND_TOTAL > 0
GROUP BY A.FACILITY_ID,
         A.LOCATION_SEQ_ID,
         A.OWNER_PARTY_ID,
         A.STATUS_ID;

SELECT *
FROM FACILITY_LOCATION FL
         LEFT JOIN FACILITY_LOCATION_INVENTORY FLI ON FLI.FACILITY_ID = FL.FACILITY_ID
    AND FLI.LOCATION_SEQ_ID = FL.LOCATION_SEQ_ID
WHERE FLI.LOCATION_SEQ_ID IS null
  and FL.FACILITY_ID = 'BOL_DC_FONTANA_2'
  AND FL.AISLE_ID IN ('02', '04', '05', '06', '07', '08', '09', '10', '12')
  AND FL.LOCATION_TYPE_ENUM_ID = 'FltPick';
/** END **/


/** ENCR-7075 **/
SELECT S.ENTRY_DATE,
       S.SHIPMENT_ID,
       S.STATUS_ID,
       S.SHIPMENT_TYPE_ENUM_ID,
       P.PSEUDO_ID,
       P.OWNER_PARTY_ID,
       SI.ORIGINAL_QUANTITY 'ORIG SHIPMENT QUANTITY',
       IFNULL(SUM(AR.QUANTITY_ACCEPTED),0) 'QUANTITY_ACCEPTED',
       IFNULL(SUM(AR.QUANTITY_REJECTED),0) 'QUANTITY_REJECTED',
       S.OTHER_PARTY_ORDER_ID,
       P.PRODUCT_NAME,
       PFTAXONOMY1.ABBREV 'TAXONOMY1',
       PFTAXONOMY2.ABBREV 'TAXONOMY2',
       PFSUPPLIER.ABBREV 'BRAND',
       PIMODELNUM.ID_VALUE 'VENDOR STYLE',
       PISTYLEID.ID_VALUE 'STYLE ID',
       PPAVGCOST.PRICE 'COST',
       PPLISTPRICE.PRICE 'LIST PRICE'
FROM SHIPMENT_ITEM SI
INNER JOIN SHIPMENT S ON S.SHIPMENT_ID = SI.SHIPMENT_ID
LEFT JOIN ASSET_RECEIPT AR ON AR.SHIPMENT_ID = SI.SHIPMENT_ID AND AR.PRODUCT_ID = SI.PRODUCT_ID
LEFT JOIN PRODUCT P ON P.PRODUCT_ID = SI.PRODUCT_ID
LEFT JOIN PRODUCT_ASSOC PA ON PA.TO_PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN (SELECT PFA.PRODUCT_ID,
            PF.PRODUCT_FEATURE_TYPE_ENUM_ID,
            PF.ABBREV,
            PF.DESCRIPTION,
            PF.OWNER_PARTY_ID
            FROM PRODUCT_FEATURE_APPL PFA
            INNER JOIN PRODUCT_FEATURE PF ON PF.PRODUCT_FEATURE_ID = PFA.PRODUCT_FEATURE_ID AND PF.PRODUCT_FEATURE_TYPE_ENUM_ID = 'PFTTAXONOMY1') PFTAXONOMY1
                    ON PFTAXONOMY1.PRODUCT_ID = PA.PRODUCT_ID
LEFT JOIN (SELECT PFA.PRODUCT_ID,
            PF.PRODUCT_FEATURE_TYPE_ENUM_ID,
            PF.ABBREV,
            PF.DESCRIPTION,
            PF.OWNER_PARTY_ID
            FROM PRODUCT_FEATURE_APPL PFA
            INNER JOIN PRODUCT_FEATURE PF ON PF.PRODUCT_FEATURE_ID = PFA.PRODUCT_FEATURE_ID AND PF.PRODUCT_FEATURE_TYPE_ENUM_ID = 'PFTTAXONOMY2') PFTAXONOMY2
                    ON PFTAXONOMY2.PRODUCT_ID = PA.PRODUCT_ID
LEFT JOIN (SELECT PFA.PRODUCT_ID,
            PF.PRODUCT_FEATURE_TYPE_ENUM_ID,
            PF.ABBREV,
            PF.DESCRIPTION,
            PF.OWNER_PARTY_ID
            FROM PRODUCT_FEATURE_APPL PFA
            INNER JOIN PRODUCT_FEATURE PF ON PF.PRODUCT_FEATURE_ID = PFA.PRODUCT_FEATURE_ID AND PF.PRODUCT_FEATURE_TYPE_ENUM_ID = 'PFTSUPPLIER') PFSUPPLIER
                    ON PFSUPPLIER.PRODUCT_ID = PA.PRODUCT_ID
LEFT JOIN (SELECT PI.PRODUCT_ID,
                  PI.ID_VALUE
    FROM PRODUCT_IDENTIFICATION PI
    WHERE PI.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTMFGMODELNUM') PIMODELNUM
        ON PIMODELNUM.PRODUCT_ID = PA.PRODUCT_ID
LEFT JOIN (SELECT PI.PRODUCT_ID,
                  PI.ID_VALUE
    FROM PRODUCT_IDENTIFICATION PI
    WHERE PI.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTSTYLEID') PISTYLEID
        ON PISTYLEID.PRODUCT_ID = PA.PRODUCT_ID
LEFT JOIN PRODUCT_PRICE PPAVGCOST ON PPAVGCOST.PRODUCT_ID = P.PRODUCT_ID
    AND PPAVGCOST.PRICE_TYPE_ENUM_ID = 'PPTAVERAGE'
    AND PPAVGCOST.PRODUCT_STORE_ID = S.PRODUCT_STORE_ID
    AND PPAVGCOST.THRU_DATE IS NULL
LEFT JOIN PRODUCT_PRICE PPLISTPRICE ON PPLISTPRICE.PRODUCT_ID = P.PRODUCT_ID
    AND PPLISTPRICE.PRICE_TYPE_ENUM_ID = 'PPTLIST'
    AND PPLISTPRICE.PRODUCT_STORE_ID = S.PRODUCT_STORE_ID
    AND PPLISTPRICE.THRU_DATE IS NULL
WHERE S.FROM_PARTY_ID = 'MODC'
AND S.OTHER_PARTY_ORDER_ID IS NOT NULL
GROUP BY SI.SHIPMENT_ID, SI.PRODUCT_ID;

SELECT P.PRODUCT_ID,
       P.PSEUDO_ID,
       A.LOCATION_SEQ_ID,
       A.FACILITY_ID,
       A.RECEIVED_DATE,
       A.STATUS_ID,
       A.OWNER_PARTY_ID,
       A.ASSET_TYPE_ENUM_ID,
       SUM(A.AVAILABLE_TO_PROMISE_TOTAL) 'ATP',
       SUM(A.QUANTITY_ON_HAND_TOTAL) 'QOH',
       PIDTUPC.ID_VALUE 'UPC',
       PISTYLEID.ID_VALUE 'STYLE ID',
       PPAVGCOST.PRICE 'COST',
       PPAVGCOST.PRICE * SUM(A.QUANTITY_ON_HAND_TOTAL) 'EXT COST',
       PFSIZE.ABBREV 'SIZE',
       PFTAXONOMY1.ABBREV 'TAXONOMY1',
       PFTAXONOMY2.ABBREV 'TAXONOMY2',
       P.PRODUCT_NAME 'DESC',
       PPLISTPRICE.PRICE 'MSRP'
FROM PRODUCT P
LEFT JOIN ASSET A ON A.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN PRODUCT_ASSOC PA ON PA.TO_PRODUCT_ID = P.PRODUCT_ID
INNER JOIN (SELECT PI.PRODUCT_ID,
                   PI.ID_VALUE
    FROM PRODUCT_IDENTIFICATION PI
    WHERE PI.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA') PIDTUPC
        ON PIDTUPC.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN (SELECT PI.PRODUCT_ID,
                  PI.ID_VALUE
    FROM PRODUCT_IDENTIFICATION PI
    WHERE PI.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTSTYLEID') PISTYLEID
        ON PISTYLEID.PRODUCT_ID = PA.PRODUCT_ID
LEFT JOIN PRODUCT_PRICE PPAVGCOST ON PPAVGCOST.PRODUCT_ID = P.PRODUCT_ID
    AND PPAVGCOST.PRICE_TYPE_ENUM_ID = 'PPTAVERAGE'
    #AND PPAVGCOST.PRODUCT_STORE_ID = S.PRODUCT_STORE_ID
    AND PPAVGCOST.THRU_DATE IS NULL
LEFT JOIN PRODUCT_PRICE PPLISTPRICE ON PPLISTPRICE.PRODUCT_ID = P.PRODUCT_ID
    AND PPLISTPRICE.PRICE_TYPE_ENUM_ID = 'PPTLIST'
    #AND PPLISTPRICE.PRODUCT_STORE_ID = S.PRODUCT_STORE_ID
    AND PPLISTPRICE.THRU_DATE IS NULL
LEFT JOIN (SELECT PFA.PRODUCT_ID,
            PF.PRODUCT_FEATURE_TYPE_ENUM_ID,
            PF.ABBREV,
            PF.DESCRIPTION,
            PF.OWNER_PARTY_ID
            FROM PRODUCT_FEATURE_APPL PFA
            INNER JOIN PRODUCT_FEATURE PF ON PF.PRODUCT_FEATURE_ID = PFA.PRODUCT_FEATURE_ID AND PF.PRODUCT_FEATURE_TYPE_ENUM_ID = 'PFTSIZE') PFSIZE
                    ON PFSIZE.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN (SELECT PFA.PRODUCT_ID,
            PF.PRODUCT_FEATURE_TYPE_ENUM_ID,
            PF.ABBREV,
            PF.DESCRIPTION,
            PF.OWNER_PARTY_ID
            FROM PRODUCT_FEATURE_APPL PFA
            INNER JOIN PRODUCT_FEATURE PF ON PF.PRODUCT_FEATURE_ID = PFA.PRODUCT_FEATURE_ID AND PF.PRODUCT_FEATURE_TYPE_ENUM_ID = 'PFTTAXONOMY1') PFTAXONOMY1
                    ON PFTAXONOMY1.PRODUCT_ID = PA.PRODUCT_ID
LEFT JOIN (SELECT PFA.PRODUCT_ID,
            PF.PRODUCT_FEATURE_TYPE_ENUM_ID,
            PF.ABBREV,
            PF.DESCRIPTION,
            PF.OWNER_PARTY_ID
            FROM PRODUCT_FEATURE_APPL PFA
            INNER JOIN PRODUCT_FEATURE PF ON PF.PRODUCT_FEATURE_ID = PFA.PRODUCT_FEATURE_ID AND PF.PRODUCT_FEATURE_TYPE_ENUM_ID = 'PFTTAXONOMY2') PFTAXONOMY2
                    ON PFTAXONOMY2.PRODUCT_ID = PA.PRODUCT_ID
WHERE P.OWNER_PARTY_ID = 'MODC';


/* On hand report */
SELECT AST.PRODUCT_ID,
       PRD.PSEUDO_ID,
       PRD.PRODUCT_NAME,
       SUM(CASE WHEN ASD.EFFECTIVE_DATE < '2023-07-01 00:00:00' THEN ASD.QUANTITY_ON_HAND_DIFF ELSE 0 END),
       SUM(CASE
               WHEN ASD.EFFECTIVE_DATE BETWEEN '2023-05-24 00:00:00' AND '2023-05-25 00:00:00'
                   THEN ASD.QUANTITY_ON_HAND_DIFF
               ELSE 0 END),
       AST.OWNER_PARTY_ID,
       SUM(CASE
               WHEN ASD.ASSET_RECEIPT_ID IS NOT NULL AND ASD.SHIPMENT_ID IS NOT NULL AND ASD.RETURN_ID IS NULL AND
                    ASD.EFFECTIVE_DATE BETWEEN '2023-05-24 00:00:00' AND '2023-05-25 00:00:00'
                   THEN ASD.QUANTITY_ON_HAND_DIFF
               ELSE 0 END),
       SUM(CASE
               WHEN ASD.ASSET_RECEIPT_ID IS NOT NULL AND ASD.RETURN_ID IS NULL AND ASD.SHIPMENT_ID IS NULL AND
                    ASD.WORK_EFFORT_ID IS NULL AND
                    ASD.EFFECTIVE_DATE BETWEEN '2023-05-24 00:00:00' AND '2023-05-25 00:00:00'
                   THEN ASD.QUANTITY_ON_HAND_DIFF
               ELSE 0 END),
       SUM(CASE
               WHEN ASD.ASSET_RECEIPT_ID IS NOT NULL AND ASD.RETURN_ID IS NOT NULL AND
                    ASD.EFFECTIVE_DATE BETWEEN '2023-05-24 00:00:00' AND '2023-05-25 00:00:00'
                   THEN ASD.QUANTITY_ON_HAND_DIFF
               ELSE 0 END),
       SUM(CASE
               WHEN ASD.ASSET_ISSUANCE_ID IS NOT NULL AND ASD.SHIPMENT_ID IS NOT NULL AND
                    ASD.EFFECTIVE_DATE BETWEEN '2023-05-24 00:00:00' AND '2023-05-25 00:00:00'
                   THEN ASD.QUANTITY_ON_HAND_DIFF
               ELSE 0 END),
       SUM(CASE
               WHEN ASD.PHYSICAL_INVENTORY_ID IS NOT NULL AND
                    ASD.EFFECTIVE_DATE BETWEEN '2023-05-24 00:00:00' AND '2023-05-25 00:00:00'
                   THEN ASD.QUANTITY_ON_HAND_DIFF
               ELSE 0 END),
       UAPI.ID_VALUE
FROM ASSET AST
         INNER JOIN ASSET_DETAIL ASD ON AST.ASSET_ID = ASD.ASSET_ID
         INNER JOIN PRODUCT PRD ON AST.PRODUCT_ID = PRD.PRODUCT_ID
         LEFT OUTER JOIN PRODUCT_IDENTIFICATION UAPI
                         ON PRD.PRODUCT_ID = UAPI.PRODUCT_ID AND UAPI.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
WHERE (AST.OWNER_PARTY_ID = 'KK' AND ASD.EFFECTIVE_DATE <= '2023-05-25 00:00:00' AND ASD.QUANTITY_ON_HAND_DIFF <> 0)
GROUP BY AST.PRODUCT_ID, PRD.PSEUDO_ID, PRD.PRODUCT_NAME, AST.OWNER_PARTY_ID, UAPI.ID_VALUE
ORDER BY PRD.PSEUDO_ID ASC;


SELECT OH.STATUS_ID,
    OI.ORDER_ID,
       OI.ORDER_PART_SEQ_ID,
       OH.DISPLAY_ID,
       OH.PRODUCT_STORE_ID,
       OH.SALES_CHANNEL_ENUM_ID,
       P.PSEUDO_ID,
       OI.ITEM_DESCRIPTION,
       OI.QUANTITY AS 'ORDER QTY',
       OI.QUANTITY_CANCELLED AS 'CANCEL QTY',
       AR.QUANTITY 'RESERVED QTY',
       AR.QUANTITY_NOT_AVAILABLE 'NOT AVAIL QTY',
       SIS.SHIPMENT_ID,
       SIS.QUANTITY,
       SIS.QUANTITY_NOT_HANDLED,
       SPC.QUANTITY,
       SIS.STATUS_ID
FROM ORDER_ITEM OI
LEFT JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.ORDER_ID = OI.ORDER_ID AND SIS.ORDER_ITEM_SEQ_ID = OI.ORDER_ITEM_SEQ_ID
INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID = OI.ORDER_ID
INNER JOIN ORDER_PART OP ON OP.ORDER_ID = OI.ORDER_ID AND OP.ORDER_PART_SEQ_ID = OI.ORDER_PART_SEQ_ID
INNER JOIN PRODUCT P ON P.PRODUCT_ID = OI.PRODUCT_ID
LEFT JOIN ASSET_RESERVATION AR ON AR.ORDER_ID = OI.ORDER_ID AND AR.ORDER_ITEM_SEQ_ID = OI.ORDER_ITEM_SEQ_ID
LEFT JOIN (SELECT SHIPMENT_ID, PRODUCT_ID, SUM(QUANTITY) AS 'QUANTITY'
           FROM SHIPMENT_PACKAGE_CONTENT
           GROUP BY SHIPMENT_ID, PRODUCT_ID) SPC ON SPC.SHIPMENT_ID = SIS.SHIPMENT_ID AND SPC.PRODUCT_ID = SIS.PRODUCT_ID
WHERE OP.VENDOR_PARTY_ID = '3361077'
AND OI.ITEM_TYPE_ENUM_ID = 'ItemProduct'
AND SIS.SHIPMENT_ID = '5511534';


## wing_jamesQuery
SELECT OI.ORDER_ID,
       OH.DISPLAY_ID,
       OH.STATUS_ID,
       OI.PRODUCT_ID,
       OI.OTHER_PARTY_PRODUCT_ID,
       OI.ITEM_DESCRIPTION,
       OI.QUANTITY,
       OI.UNIT_AMOUNT
FROM ORDER_ITEM OI
         JOIN ORDER_PART OP ON OI.ORDER_ID = OP.ORDER_ID
         JOIN ORDER_HEADER OH ON OP.ORDER_ID = OH.ORDER_ID
WHERE PRODUCT_STORE_ID = 'SG_101174'
  AND OP.FACILITY_ID = 'BOL_DC_FONTANA_2'
  AND OI.ITEM_TYPE_ENUM_ID = 'ItemProduct'
  AND OI.PRODUCT_ID <> 1907519
ORDER BY OI.ORDER_ID;

/*james_shipmentAndTracking*/
SELECT OI.ORDER_ID,
       OI.ORDER_ITEM_SEQ_ID,
       OI.ORDER_PART_SEQ_ID,
       OI.QUANTITY AS 'ORDER QTY',
       SIS.QUANTITY AS 'SHIP QTY',
       P.PSEUDO_ID AS 'SKU',
       PI.ID_VALUE AS 'UPCA',
       SIS.SHIPMENT_ID,
       OH.DISPLAY_ID,
       OH.PLACED_DATE,
       OH.PRODUCT_STORE_ID,
       PS.STORE_NAME,
       OH.STATUS_ID AS 'ORDER STATUS',
       S.STATUS_ID AS 'SHIPMENT STATUS',
       P.PRODUCT_NAME,
       S.PACKED_DATE,
       SRS.ORIGIN_FACILITY_ID,
       SRS.CARRIER_PARTY_ID,
       SRS.SHIPMENT_METHOD_ENUM_ID,
       SPRS.TRACKING_CODE,
       SPRS.SHIPMENT_PACKAGE_SEQ_ID
FROM SHIPMENT_ITEM_SOURCE SIS
INNER JOIN ORDER_ITEM OI ON OI.ORDER_ID = SIS.ORDER_ID
    AND OI.ORDER_ITEM_SEQ_ID = SIS.ORDER_ITEM_SEQ_ID
INNER JOIN PRODUCT P ON P.PRODUCT_ID = SIS.PRODUCT_ID
    AND P.PRODUCT_CLASS_ENUM_ID IS NULL
LEFT OUTER JOIN PRODUCT_IDENTIFICATION PI ON PI.PRODUCT_ID = P.PRODUCT_ID
    AND PI.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
INNER JOIN SHIPMENT S ON S.SHIPMENT_ID = SIS.SHIPMENT_ID
    AND S.STATUS_ID IN ('SHIPSHIPPED','SHIPDELIVERED')
INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID = OI.ORDER_ID
INNER JOIN PRODUCT_STORE PS ON PS.PRODUCT_STORE_ID = OH.PRODUCT_STORE_ID
INNER JOIN SHIPMENT_PACKAGE_CONTENT SPC ON SPC.SHIPMENT_ID = SIS.SHIPMENT_ID
    AND SPC.PRODUCT_ID = SIS.PRODUCT_ID
INNER JOIN SHIPMENT_ROUTE_SEGMENT SRS ON SRS.SHIPMENT_ID = S.SHIPMENT_ID
INNER JOIN SHIPMENT_PACKAGE_ROUTE_SEG SPRS ON SPRS.SHIPMENT_ID = S.SHIPMENT_ID
    AND SPRS.SHIPMENT_ROUTE_SEGMENT_SEQ_ID = SRS.SHIPMENT_ROUTE_SEGMENT_SEQ_ID
    AND SPRS.SHIPMENT_PACKAGE_SEQ_ID = SPC.SHIPMENT_PACKAGE_SEQ_ID
WHERE SRS.ORIGIN_FACILITY_ID IN ('BOL_DC_FONTANA','BOL_DC_FONTANA_2','NOG_DC_PITTSBURGH_FACILITY')
AND SIS.QUANTITY > 0
AND S.PACKED_DATE BETWEEN '2021-01-01 00:00' AND '2022-01-01 00:00'
#AND S.SHIPMENT_ID = '5649011';

/*
 shipments and returns by brand by sku by tracking for 2021 & 2022
 today's atp and qoh
 incoming flow by sku by month
 ENCR-8181
 added address info
 */
SELECT RI.ORDER_ID,
       RH.DISPLAY_ID,
       RH.ENTRY_DATE,
       RH.RETURN_ID,
       RH.STATUS_ID,
       RH.VENDOR_PARTY_ID,
       RH.FACILITY_ID,
       P.PRODUCT_NAME,
       SI.PRODUCT_ID,
       P.PSEUDO_ID,
       PIUPCA.ID_VALUE AS 'UPCA',
       AR.RECEIVED_DATE,
       AR.QUANTITY_ACCEPTED,
       SPRS.RETURN_TRACKING_CODE,
       RH.CARRIER_PARTY_ID,
       RH.SHIPMENT_METHOD_ENUM_ID,
       RH.ORIGIN_ID,
       CUST_PA.CITY,
       CUST_PA.POSTAL_CODE,
       CUST_PA.RAW_PROVINCE,
       CUST_PA.STATE_PROVINCE_GEO_ID,
       WHSE_PA.POSTAL_CODE
FROM RETURN_HEADER RH
INNER JOIN RETURN_ITEM RI ON RI.RETURN_ID = RH.RETURN_ID
INNER JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.RETURN_ID = RI.RETURN_ID AND SIS.RETURN_ITEM_SEQ_ID = RI.RETURN_ITEM_SEQ_ID
INNER JOIN SHIPMENT_ITEM SI ON SI.SHIPMENT_ID = SIS.SHIPMENT_ID AND SI.PRODUCT_ID = SIS.PRODUCT_ID
INNER JOIN ASSET_RECEIPT AR ON AR.SHIPMENT_ID = SIS.SHIPMENT_ID AND AR.RETURN_ID = SIS.RETURN_ID AND AR.RETURN_ITEM_SEQ_ID = SIS.RETURN_ITEM_SEQ_ID
INNER JOIN PRODUCT P ON P.PRODUCT_ID = SI.PRODUCT_ID
INNER JOIN PRODUCT_IDENTIFICATION PIUPCA ON PIUPCA.PRODUCT_ID = P.PRODUCT_ID AND PIUPCA.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
INNER JOIN ORDER_ITEM OI ON OI.ORDER_ID = RI.ORDER_ID AND OI.ORDER_ITEM_SEQ_ID = RI.ORDER_ITEM_SEQ_ID
INNER JOIN ORDER_PART OP ON OP.ORDER_ID = OI.ORDER_ID AND OP.ORDER_PART_SEQ_ID = OI.ORDER_PART_SEQ_ID
INNER JOIN POSTAL_ADDRESS CUST_PA ON CUST_PA.CONTACT_MECH_ID = OP.POSTAL_CONTACT_MECH_ID
LEFT JOIN FACILITY_CONTACT_MECH FCM ON FCM.FACILITY_ID = RH.FACILITY_ID AND FCM.CONTACT_MECH_PURPOSE_ID = 'POSTALPRIMARY' AND FCM.THRU_DATE IS NULL
LEFT JOIN POSTAL_ADDRESS WHSE_PA ON WHSE_PA.CONTACT_MECH_ID = FCM.CONTACT_MECH_ID
LEFT JOIN SHIPMENT_PACKAGE_ROUTE_SEG SPRS ON SPRS.SHIPMENT_ID = SI.SHIPMENT_ID
WHERE RH.ENTRY_DATE BETWEEN '2022-01-01 00:00:00' AND '2023-01-01 00:00:00'
ORDER BY RH.ENTRY_DATE DESC;



---- original
SELECT RI.ORDER_ID,
       RH.DISPLAY_ID,
       RH.ENTRY_DATE,
       RH.RETURN_ID,
       RH.STATUS_ID,
       RH.VENDOR_PARTY_ID,
       RH.FACILITY_ID,
       P.PRODUCT_NAME,
       SI.PRODUCT_ID,
       P.PSEUDO_ID,
       PIUPCA.ID_VALUE AS 'UPCA',
       AR.RECEIVED_DATE,
       AR.QUANTITY_ACCEPTED,
       SPRS.RETURN_TRACKING_CODE,
       RH.CARRIER_PARTY_ID,
       RH.SHIPMENT_METHOD_ENUM_ID,
       RH.ORIGIN_ID
FROM RETURN_HEADER RH
INNER JOIN RETURN_ITEM RI ON RI.RETURN_ID = RH.RETURN_ID
INNER JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.RETURN_ID = RI.RETURN_ID AND SIS.RETURN_ITEM_SEQ_ID = RI.RETURN_ITEM_SEQ_ID
INNER JOIN SHIPMENT_ITEM SI ON SI.SHIPMENT_ID = SIS.SHIPMENT_ID AND SI.PRODUCT_ID = SIS.PRODUCT_ID
INNER JOIN ASSET_RECEIPT AR ON AR.SHIPMENT_ID = SIS.SHIPMENT_ID AND AR.RETURN_ID = SIS.RETURN_ID AND AR.RETURN_ITEM_SEQ_ID = SIS.RETURN_ITEM_SEQ_ID
INNER JOIN PRODUCT P ON P.PRODUCT_ID = SI.PRODUCT_ID
INNER JOIN PRODUCT_IDENTIFICATION PIUPCA ON PIUPCA.PRODUCT_ID = P.PRODUCT_ID AND PIUPCA.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
LEFT JOIN SHIPMENT_PACKAGE_ROUTE_SEG SPRS ON SPRS.SHIPMENT_ID = SI.SHIPMENT_ID
WHERE RH.ENTRY_DATE BETWEEN '2022-01-01 00:00:00' AND '2023-01-01 00:00:00'
ORDER BY RH.ENTRY_DATE DESC;


/*
 ricky
 */
SELECT OI.ORDER_ID,
       OI.ORDER_ITEM_SEQ_ID,
       OI.ORDER_PART_SEQ_ID,
       OI.QUANTITY AS 'ORDER QTY',
       SIS.QUANTITY AS 'SHIP QTY',
       P.PSEUDO_ID AS 'SKU',
       PI.ID_VALUE AS 'UPCA',
       SIS.SHIPMENT_ID,
       OH.DISPLAY_ID,
       OH.PLACED_DATE,
       OH.PRODUCT_STORE_ID,
       PS.STORE_NAME,
       OH.GRAND_TOTAL, OP.PART_TOTAL, OH.CURRENCY_UOM_ID,
       OH.STATUS_ID AS 'ORDER STATUS',
       S.STATUS_ID AS 'SHIPMENT STATUS',
       P.PRODUCT_NAME,
       S.PACKED_DATE,
       SRS.ORIGIN_FACILITY_ID,
       SRS.CARRIER_PARTY_ID,
       SRS.SHIPMENT_METHOD_ENUM_ID,
       SP.SHIPMENT_BOX_TYPE_ID,
       SBT.DESCRIPTION,
       SP.WEIGHT,
       SP.WEIGHT_UOM_ID,
       SPRS.TRACKING_CODE,
       SPRS.SHIPMENT_PACKAGE_SEQ_ID,
       OP.SHIPMENT_METHOD_ENUM_ID, OP.CARRIER_PARTY_ID,
       PA.CITY,PA.RAW_PROVINCE, PA.POSTAL_CODE
FROM SHIPMENT_ITEM_SOURCE SIS
INNER JOIN ORDER_ITEM OI ON OI.ORDER_ID = SIS.ORDER_ID
    AND OI.ORDER_ITEM_SEQ_ID = SIS.ORDER_ITEM_SEQ_ID
INNER JOIN PRODUCT P ON P.PRODUCT_ID = SIS.PRODUCT_ID
    AND P.PRODUCT_CLASS_ENUM_ID IS NULL
LEFT OUTER JOIN PRODUCT_IDENTIFICATION PI ON PI.PRODUCT_ID = P.PRODUCT_ID
    AND PI.PRODUCT_ID_TYPE_ENUM_ID = 'PidtUpca'
INNER JOIN SHIPMENT S ON S.SHIPMENT_ID = SIS.SHIPMENT_ID
    AND S.STATUS_ID IN ('SHIPSHIPPED','SHIPDELIVERED')
INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID = OI.ORDER_ID
inner join ORDER_PART OP on OP.ORDER_ID = OH.ORDER_ID
inner join POSTAL_ADDRESS PA on OP.POSTAL_CONTACT_MECH_ID = PA.CONTACT_MECH_ID
INNER JOIN PRODUCT_STORE PS ON PS.PRODUCT_STORE_ID = OH.PRODUCT_STORE_ID
INNER JOIN SHIPMENT_PACKAGE_CONTENT SPC ON SPC.SHIPMENT_ID = SIS.SHIPMENT_ID
    AND SPC.PRODUCT_ID = SIS.PRODUCT_ID
left join SHIPMENT_PACKAGE SP ON SP.SHIPMENT_ID = SIS.SHIPMENT_ID
left join SHIPMENT_BOX_TYPE SBT ON SBT.SHIPMENT_BOX_TYPE_ID = SP.SHIPMENT_BOX_TYPE_ID
INNER JOIN SHIPMENT_ROUTE_SEGMENT SRS ON SRS.SHIPMENT_ID = S.SHIPMENT_ID
INNER JOIN SHIPMENT_PACKAGE_ROUTE_SEG SPRS ON SPRS.SHIPMENT_ID = S.SHIPMENT_ID
    AND SPRS.SHIPMENT_ROUTE_SEGMENT_SEQ_ID = SRS.SHIPMENT_ROUTE_SEGMENT_SEQ_ID
    AND SPRS.SHIPMENT_PACKAGE_SEQ_ID = SPC.SHIPMENT_PACKAGE_SEQ_ID
WHERE SRS.ORIGIN_FACILITY_ID IN ('BOL_DC_FONTANA','BOL_DC_FONTANA_2','NOG_DC_PITTSBURGH_FACILITY')
AND SIS.QUANTITY > 0
AND S.PACKED_DATE > '2022-01-01 00:00'
and OH.PRODUCT_STORE_ID = 'JUST_SHOPIFY'
ORDER BY OH.PLACED_DATE;

SELECT
    P.PSEUDO_ID,
    P.PRODUCT_ID,
    SUM(CASE
        WHEN OH.PLACED_DATE BETWEEN '2022-01-01 00:00' AND '2022-02-01 00:00'
        THEN OI.QUANTITY
        ELSE 0 END) AS 'JAN',
    SUM(CASE
        WHEN OH.PLACED_DATE BETWEEN '2022-02-01 00:00' AND '2022-03-01 00:00'
        THEN OI.QUANTITY
        ELSE 0 END) AS 'FEB',
    SUM(CASE
        WHEN OH.PLACED_DATE BETWEEN '2022-03-01 00:00' AND '2022-04-01 00:00'
        THEN OI.QUANTITY
        ELSE 0 END) AS 'MAR',
    SUM(CASE
        WHEN OH.PLACED_DATE BETWEEN '2022-04-01 00:00' AND '2022-05-01 00:00'
        THEN OI.QUANTITY
        ELSE 0 END) AS 'APR'
FROM ORDER_HEADER OH
INNER JOIN ORDER_PART OP ON OP.ORDER_ID = OH.ORDER_ID AND OH.STATUS_ID IN ('ORDERAPPROVED','ORDERCOMPLETED')
INNER JOIN ORDER_ITEM OI ON OI.ORDER_ID = OP.ORDER_ID AND OI.ORDER_PART_SEQ_ID = OP.ORDER_PART_SEQ_ID
INNER JOIN PRODUCT P ON P.PRODUCT_ID = OI.PRODUCT_ID
WHERE OP.VENDOR_PARTY_ID = 'HRLY'
AND OH.PLACED_DATE BETWEEN '2023-08-01 00:00' AND '2023-08-31 00:00'
AND OP.FACILITY_ID IN ('NOG_DC_PITTSBURGH_FACILITY','BOL_DC_FONTANA','BOL_DC_FONTANA_2','NOG_DC_COMPTON')
GROUP BY P.PRODUCT_ID
LIMIT 10;

select * FROM OUTBOUND_SHIPMENT_STATS limit 100;

/*
 Receipts
 */
SELECT P.PSEUDO_ID,
       A.PRODUCT_ID,
       A.QUANTITY_ON_HAND_TOTAL AS 'CURRENT OH',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-01-01 00:00' AND '2022-02-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'JAN22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-02-01 00:00' AND '2022-03-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'FEB22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-03-01 00:00' AND '2022-04-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'MAR22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-04-01 00:00' AND '2022-05-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'APR22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-05-01 00:00' AND '2022-06-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'MAY22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-06-01 00:00' AND '2022-07-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'JUN22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-07-01 00:00' AND '2022-08-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'JUL22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-08-01 00:00' AND '2022-09-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'AUG22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-09-01 00:00' AND '2022-10-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'SEP22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-10-01 00:00' AND '2022-11-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'OCT22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-11-01 00:00' AND '2022-12-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'NOV22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2022-12-01 00:00' AND '2023-01-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'DEC22',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2023-01-01 00:00' AND '2023-02-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'JAN23',
       SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2023-02-01 00:00' AND '2023-03-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'FEB23',
    SUM(CASE WHEN AD.EFFECTIVE_DATE BETWEEN '2023-03-01 00:00' AND '2023-04-01 00:00'
           THEN AD.QUANTITY_ON_HAND_DIFF
           ELSE 0 END) AS 'MAR23'
FROM ASSET A
INNER JOIN ASSET_DETAIL AD ON AD.ASSET_ID = A.ASSET_ID AND AD.ASSET_RECEIPT_ID IS NOT NULL AND AD.SHIPMENT_ID IS NOT NULL
INNER JOIN PRODUCT P ON P.PRODUCT_ID = A.PRODUCT_ID
INNER JOIN ASSET_RECEIPT AR ON AR.ASSET_RECEIPT_ID = AD.ASSET_RECEIPT_ID
WHERE A.OWNER_PARTY_ID = 'IMHD'
AND A.FACILITY_ID = 'NOG_DC_PITTSBURGH_FACILITY'
AND AR.RECEIVED_DATE > '2022-01-01 00:00'
GROUP BY A.PRODUCT_ID, P.PSEUDO_ID;

SELECT *
FROM ASSET_DETAIL AD
INNER JOIN ASSET_RECEIPT AR ON AR.ASSET_RECEIPT_ID = AD.ASSET_RECEIPT_ID
INNER JOIN ASSET A ON A.ASSET_ID = AD.ASSET_ID
WHERE AD.PRODUCT_ID = '1944311'
AND AD.EFFECTIVE_DATE > '2023-01-01 00:00'
AND AD.ASSET_RECEIPT_ID IS NOT NULL;

/*ENCR-8073 | INV AGING REPORT*/
SELECT P.PSEUDO_ID AS 'SKU',
       PI.ID_VALUE AS 'UPCA',
       P.PRODUCT_NAME AS 'NAME',
       A.FACILITY_ID,
       SUM(CASE WHEN A.QUANTITY_ON_HAND_TOTAL > 0 THEN A.QUANTITY_ON_HAND_TOTAL ELSE 0 END) AS 'CURRENT',
       SUM(CASE
           WHEN DATEDIFF(CURDATE(),DATE(A.RECEIVED_DATE)) < 30
               THEN A.QUANTITY_ON_HAND_TOTAL
           ELSE 0 END) AS '0-30 DAYS',
       SUM(CASE
           WHEN DATEDIFF(CURDATE(),DATE(A.RECEIVED_DATE)) BETWEEN 31 AND 60
               THEN A.QUANTITY_ON_HAND_TOTAL
           ELSE 0 END) AS '31-60 DAYS',
       SUM(CASE
           WHEN DATEDIFF(CURDATE(),DATE(A.RECEIVED_DATE)) BETWEEN 61 AND 90
               THEN A.QUANTITY_ON_HAND_TOTAL
           ELSE 0 END) AS '61-90 DAYS',
       SUM(CASE
           WHEN DATEDIFF(CURDATE(),DATE(A.RECEIVED_DATE)) BETWEEN 91 AND 120
               THEN A.QUANTITY_ON_HAND_TOTAL
           ELSE 0 END) AS '91-120 DAYS',
       SUM(CASE
           WHEN DATEDIFF(CURDATE(),DATE(A.RECEIVED_DATE)) BETWEEN 121 AND 180
               THEN A.QUANTITY_ON_HAND_TOTAL
           ELSE 0 END) AS '121-180 DAYS',
       SUM(CASE
           WHEN DATEDIFF(CURDATE(),DATE(A.RECEIVED_DATE)) BETWEEN 181 AND 365
               THEN A.QUANTITY_ON_HAND_TOTAL
           ELSE 0 END) AS '181-365 DAYS',
       SUM(CASE
           WHEN DATEDIFF(CURDATE(),DATE(A.RECEIVED_DATE)) > 365
               THEN A.QUANTITY_ON_HAND_TOTAL
           ELSE 0 END) AS '> 365 DAYS'
FROM PRODUCT P
INNER JOIN ASSET A ON A.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN PRODUCT_IDENTIFICATION PI ON PI.PRODUCT_ID = P.PRODUCT_ID AND PI.PRODUCT_ID_TYPE_ENUM_ID = 'PIDTUPCA'
WHERE P.OWNER_PARTY_ID = 'KCNY'
GROUP BY P.PSEUDO_ID, PI.ID_VALUE, P.PRODUCT_NAME, A.FACILITY_ID;



/*jamesyoon_returnlineitems*/
SELECT RH.DISPLAY_ID,
       RH.VENDOR_PARTY_ID,
       RH.ENTRY_DATE,
       RH.STATUS_ID 'RETURN STATUS',
       RI.PRODUCT_ID,
       P.PSEUDO_ID,
       RI.ITEM_TYPE_ENUM_ID,
       RI.STATUS_ID 'ITEM STATUS',
       SIS.QUANTITY,
       SIS.QUANTITY_NOT_HANDLED,
       S.STATUS_ID,
       RI.RETURN_RESPONSE_ENUM_ID,
       RI.RESPONSE_DATE
FROM RETURN_HEADER RH
INNER JOIN RETURN_ITEM RI ON RI.RETURN_ID = RH.RETURN_ID
INNER JOIN PRODUCT P ON P.PRODUCT_ID = RI.PRODUCT_ID
INNER JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.RETURN_ID = RI.RETURN_ID AND SIS.RETURN_ITEM_SEQ_ID = RI.RETURN_ITEM_SEQ_ID
INNER JOIN SHIPMENT S ON SIS.SHIPMENT_ID
WHERE RI.ITEM_TYPE_ENUM_ID = 'ITEMPRODUCT'
AND RH.VENDOR_PARTY_ID = 'BEBE'
AND RH.ENTRY_DATE BETWEEN '2022-02-01' AND '2022-04-01'
ORDER BY RH.ENTRY_DATE DESC;

/*
 requested by Andy (or really, Arash)
 Client Billing | Sales Shipping Label Cost
 */
-- ShippingSalesLabelCost
SELECT OP.VENDOR_PARTY_ID as 'Client',
       SRS.ORIGIN_FACILITY_ID as 'Facility',
       PA2.POSTAL_CODE AS 'Facility Zip',
       S.PACKED_DATE as 'Date',
       PA.TO_NAME as 'Customer Name',
       OH.DISPLAY_ID as 'Order Number',
       OH.EXTERNAL_ID as 'External Id',
       SPRS.ESTIMATED_AMOUNT as 'Cost',
       SPRS.TRACKING_CODE as 'Tracking Code',
       SRS.CARRIER_PARTY_ID as 'Carrier',
       SRS.SHIPMENT_METHOD_ENUM_ID as 'Method',
       PA.POSTAL_CODE as 'Destination Zip',
       SBT.DESCRIPTION as 'Package Type',
       SP.WEIGHT as 'Package Weight',
       CONCAT(UOM.DESCRIPTION,' (',UOM.ABBREVIATION,')') as 'Package Weight Uom'
FROM SHIPMENT_ROUTE_SEGMENT SRS
INNER JOIN SHIPMENT S ON S.SHIPMENT_ID = SRS.SHIPMENT_ID
INNER JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.SHIPMENT_ID = SRS.SHIPMENT_ID
INNER JOIN ORDER_ITEM OI ON OI.ORDER_ID = SIS.ORDER_ID AND OI.PRODUCT_ID = SIS.PRODUCT_ID
INNER JOIN ORDER_PART OP ON OP.ORDER_ID = OI.ORDER_ID AND OP.ORDER_PART_SEQ_ID = OI.ORDER_PART_SEQ_ID
INNER JOIN ORDER_HEADER OH ON OH.ORDER_ID = OP.ORDER_ID
INNER JOIN SHIPMENT_PACKAGE_ROUTE_SEG SPRS ON SPRS.SHIPMENT_ID = SRS.SHIPMENT_ID AND SPRS.SHIPMENT_ROUTE_SEGMENT_SEQ_ID = SRS.SHIPMENT_ROUTE_SEGMENT_SEQ_ID
INNER JOIN POSTAL_ADDRESS PA ON PA.CONTACT_MECH_ID = SRS.DEST_POSTAL_CONTACT_MECH_ID
INNER JOIN SHIPMENT_PACKAGE SP ON SP.SHIPMENT_ID = SPRS.SHIPMENT_ID AND SP.SHIPMENT_PACKAGE_SEQ_ID = SPRS.SHIPMENT_PACKAGE_SEQ_ID
INNER JOIN SHIPMENT_BOX_TYPE SBT ON SBT.SHIPMENT_BOX_TYPE_ID = SP.SHIPMENT_BOX_TYPE_ID
INNER JOIN UOM ON UOM.UOM_ID = SP.WEIGHT_UOM_ID
INNER JOIN FACILITY_CONTACT_MECH FCM ON FCM.FACILITY_ID = SRS.ORIGIN_FACILITY_ID AND FCM.THRU_DATE IS NULL AND FCM.CONTACT_MECH_PURPOSE_ID = 'PostalPrimary'
INNER JOIN POSTAL_ADDRESS PA2 ON PA2.CONTACT_MECH_ID = FCM.CONTACT_MECH_ID
WHERE SRS.ORIGIN_FACILITY_ID = 'BOL_DC_FONTANA_2'
AND S.PACKED_DATE BETWEEN '2023-01-01 00:00' AND '2023-06-29 00:00'
GROUP BY OP.VENDOR_PARTY_ID, SRS.ORIGIN_FACILITY_ID, PA2.POSTAL_CODE, S.PACKED_DATE, PA.TO_NAME, OH.DISPLAY_ID, OH.EXTERNAL_ID, SPRS.ESTIMATED_AMOUNT, SPRS.TRACKING_CODE, SRS.CARRIER_PARTY_ID, SRS.SHIPMENT_METHOD_ENUM_ID, PA.POSTAL_CODE, SBT.DESCRIPTION, SP.WEIGHT
ORDER BY S.PACKED_DATE DESC;


/*
 asset summary for liz bai
 */
SELECT '' as 'Assets',
       P.PSEUDO_ID as 'Product ID',
       P.PRODUCT_NAME as 'Product Name',
       A.CLASS_ENUM_ID as 'Asset Class',
       A.STATUS_ID as 'Status',
       A.OWNER_PARTY_ID as 'Owner Party',
       A.ASSET_POOL_ID as 'Asset Pool',
       A.FACILITY_ID as 'Facility',
       A.LOCATION_SEQ_ID as 'Location',
       A.LOT_ID as 'Lot',
       SUM(A.AVAILABLE_TO_PROMISE_TOTAL) as 'Available',
       SUM(A.QUANTITY_ON_HAND_TOTAL) as 'On Hand',
       '' as 'Phl Qty',
       '' as 'Move'
FROM ASSET A
INNER JOIN PRODUCT P ON P.PRODUCT_ID = A.PRODUCT_ID
WHERE A.OWNER_PARTY_ID = 'JUST'
#AND A.STATUS_ID = 'ASTONHOLD'
AND A.QUANTITY_ON_HAND_TOTAL > 0
AND A.FACILITY_ID IN ('BOL_DC_FONTANA_2', 'NOG_DC_PITTSBURGH_FACILITY')
GROUP BY A.PRODUCT_ID, A.STATUS_ID, A.OWNER_PARTY_ID, A.ASSET_POOL_ID, A.FACILITY_ID, A.LOCATION_SEQ_ID, A.LOT_ID;

SELECT DISTINCT A.STATUS_ID
FROM ASSET A
WHERE A.OWNER_PARTY_ID = 'JUST'
AND A.QUANTITY_ON_HAND_TOTAL > 0
AND A.FACILITY_ID = 'NOG_DC_PITTSBURGH_FACILITY';

SELECT *
FROM ORDER_HEADER OH
INNER JOIN ORDER_PART OP ON OP.ORDER_ID = OH.ORDER_ID
INNER JOIN ORDER_ITEM OI ON OI.ORDER_ID = OP.ORDER_ID AND OI.ORDER_PART_SEQ_ID = OP.ORDER_PART_SEQ_ID
INNER JOIN SHIPMENT_ITEM_SOURCE SIS ON SIS.ORDER_ID = OI.ORDER_ID AND SIS.ORDER_ITEM_SEQ_ID = OI.ORDER_ITEM_SEQ_ID
INNER JOIN SHIPMENT S ON S.SHIPMENT_ID = SIS.SHIPMENT_ID
WHERE OH.PRODUCT_STORE_ID = 'HRLY_SHOPIFY'
AND OH.PLACED_DATE BETWEEN '2023-08-01 00:00:00' AND '2023-09-01 00:00:00';
